### ISSUE TITLE
list_devices() details flag hangs the program.

### ISSUE THREAD

**Issue by DaanSelen** [HuFlungDu/pylibmeshctrl#10]
Hello Hungfludu,

The function `list_devices()` specifically with the details=True flag seems to be hanging the program.

```
Parameters:

        details ([bool](https://docs.python.org/3.13/library/functions.html#bool)) – Get device details, overrides group and meshid
```

```
raw_devices = await session.list_devices(details=True)
```

This takes a long while.

```
(venv) dselen@NB-DS-O1234-Win:~$ python3 rewrite.py
```

**Comment by DaanSelen** [comment]
I have looked around and I do not know what would be going wrong. The only thing I change is the details flag to True and it no longer responds, leave it false and it works.

**Comment by HuFlungDu** [comment]
The only await when details is true is in the taskgroup. The interesting thing here is that details needs to uses send_command_no_response_id, which turns it into a non-namespaced call, so it's possible something about your enviconment is making that not work, but I don't know how to replicate.  That can also be an issue if you call the same command multiple times without awaiting, but I doubt that's what you are doing.

Can you put this code in your call with list_devices and post the output?:

```python
async def _(session):
    async for message in session.raw_messages():
        print(message)
async with asyncio.TaskGroup() as tg:
    tg.create_task(asyncio.wait_for(_(session), timeout=5))
    tg.create_task(session.list_devices(details=True, timeout=5))
```

That will print all the messages the meshcentral server sends to the session, so we can check if it gives us anything back. Be careful to wipe anything you don't want to share publicly (deviceids, meshids, cookies, etc).

**Comment by DaanSelen** [comment]
Excuse my incompetence but where exactly?

My main function is like:
```
async def main():
    try:
        configuration = load_config()

        session = meshctrl.Session(
            configuration['websocket_url'],
            user=configuration['username'],
            password=configuration['password']
        )
        await session.initialized.wait()

        raw_devices = await session.list_devices()
        for device in raw_devices:
            device = device.__dict__
            print(json.dumps(device, indent=4, default=translation_function))

    except Exception as e:
        print(f"Error occurred: {e}")
    finally:
        if session:
            await session.close()

asyncio.run(main())
```

**Comment by HuFlungDu** [comment]
Replace list_devices:

```python

async def main():
    try:
        configuration = load_config()

        session = meshctrl.Session(
            configuration['websocket_url'],
            user=configuration['username'],
            password=configuration['password']
        )
        await session.initialized.wait()

        async def _(session):
            async for message in session.raw_messages():
                print(message)
        async with asyncio.TaskGroup() as tg:
            tg.create_task(asyncio.wait_for(_(session), timeout=5))
            tg.create_task(session.list_devices(details=True, timeout=5))
        for device in raw_devices:
            device = device.__dict__
            print(json.dumps(device, indent=4, default=translation_function))

    except Exception as e:
        print(f"Error occurred: {e}")
    finally:
        if session:
            await session.close()

asyncio.run(main())
```

It'll probably error because of the timeout, but that's fine for now, we just want to see the raw messages from the server.

**Comment by DaanSelen** [comment]
```
(venv) celdrith@N-DESKTOP1:~/meshcaller$ cat rewrite.py
import asyncio
from base64 import b64encode
from configparser import ConfigParser
import datetime
import json
import meshctrl
import os
import re

class ScriptEndTrigger(Exception):
    pass

def base64_encode(string: str): # Encode to Base64 encoding.
    return b64encode(string.encode('utf-8')).decode()

def load_config(conffile=None, segment='meshcentral-account'):
    if conffile is None:
        conffile = './api.conf'

    if not os.path.exists(conffile):
        raise ScriptEndTrigger(f'Missing config file {conffile}, unable to initialize. Please provide an alternative path.')

    try:
        my_config = ConfigParser()
        my_config.read(conffile)
    except Exception as err:
        raise ScriptEndTrigger(f'Unable to read config file <{conffile}>: {err}!')

    if segment not in my_config:
        raise ScriptEndTrigger(f'Segment "{segment}" not found in config file <{conffile}>!')

    return my_config[segment]

def translation_function(obj):
    if isinstance(obj, datetime.datetime):
        return obj.isoformat()
    return str(obj)

async def main():
    try:
        configuration = load_config()

        session = meshctrl.Session(
            configuration['websocket_url'],
            user=configuration['username'],
            password=configuration['password']
        )
        await session.initialized.wait()

        async def _(session):
            async for message in session.raw_messages():
                print(message)
        async with asyncio.TaskGroup() as tg:
            tg.create_task(asyncio.wait_for(_(session), timeout=5))
            tg.create_task(session.list_devices(details=True, timeout=5))

        for device in raw_devices:
            device = device.__dict__
            print(json.dumps(device, indent=4, default=translation_function))

    except Exception as e:
        print(f"Error occurred: {e}")
    finally:
        if session:
            await session.close()

asyncio.run(main())(venv) celdrith@N-DESKTOP1:~/meshcaller$ python3 rewrite.py
Error occurred: unhandled errors in a TaskGroup (2 sub-exceptions)
```
This is the result, and thank you for your help already!

**Comment by HuFlungDu** [comment]
Oops, you're swallowing the exceptions. Just get rid of the catch for now. I'm assuming the exceptions are just timeouts, but I can't tell from here.

Anyway, it should still be printing the raw messages, maybe it's not returning anything for some reason. Can you add the list_devices with false to the task_group?

```python

    async with asyncio.TaskGroup() as tg:
        tg.create_task(asyncio.wait_for(_(session), timeout=5))
        tg.create_task(session.list_devices(details=False, timeout=5))
        tg.create_task(session.list_devices(details=True, timeout=5))
```

Also, it might be nicer to user an async context manager than a try, except:

```python

async def main():
    configuration = load_config()

    async with meshctrl.Session(
        configuration['websocket_url'],
        user=configuration['username'],
        password=configuration['password']
    ) as session:
        await session.initialized.wait()

        async def _(session):
            async for message in session.raw_messages():
                print(message)
        async with asyncio.TaskGroup() as tg:
            tg.create_task(asyncio.wait_for(_(session), timeout=5))
            tg.create_task(session.list_devices(details=True, timeout=5))

        for device in raw_devices:
            device = device.__dict__
            print(json.dumps(device, indent=4, default=translation_function))

```

It will automatically handle teardown. If you have a reason to not do that (non-specific life time for the session, for example) then feel free to ignore that, but I find the context manager to be nicer.

**Comment by DaanSelen** [comment]
Okay what i get now is the wait for, then followed by the actual output generated by the `False` details call.

Then...
```
  + Exception Group Traceback (most recent call last):
  |   File "/home/celdrith/meshcaller/rewrite.py", line 61, in <module>
  |     asyncio.run(main())
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/home/celdrith/meshcaller/rewrite.py", line 52, in main
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    |     return fut.result()
    |            ^^^^^^^^^^^^
    |   File "/home/celdrith/meshcaller/rewrite.py", line 50, in _
    |     async for message in session.raw_messages():
    |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 533, in raw_messages
    |     data = await event_queue.get()
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/asyncio/queues.py", line 158, in get
    |     await getter
    | asyncio.exceptions.CancelledError
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    |     raise exceptions.TimeoutError() from exc
    | TimeoutError
    +---------------- 2 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 466, in list_devices
    |     async with asyncio.TaskGroup() as tg:
    |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
      |     return fut.result()
      |            ^^^^^^^^^^^^
      |   File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
      |     await fut
      | asyncio.exceptions.CancelledError
      |
      | The above exception was the direct cause of the following exception:
      |
      | Traceback (most recent call last):
      |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/util.py", line 154, in wrapper
      |     return await f(self, *args, **kwargs)
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 268, in _send_command_no_response_id
      |     await asyncio.wait_for(responded.wait(), timeout=timeout)
      |   File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
      |     raise exceptions.TimeoutError() from exc
      | TimeoutError
      +------------------------------------
```

**Comment by HuFlungDu** [comment]
Can you post the full, redacted output? Just want to make sure I'm seeing everything.

Also, I should have already asked, which version of meshcentral are you using? If it's not returning anything, it could not support that command, so I'll need to test and maybe handle that if a version is not available.

**Comment by DaanSelen** [comment]
If you have time I can hop onto a chat, if you are available for that, otherwise here are the details:

Full script
```python
import asyncio
from base64 import b64encode
from configparser import ConfigParser
import datetime
import json
import meshctrl
import os
import re

class ScriptEndTrigger(Exception):
    pass

def base64_encode(string: str): # Encode to Base64 encoding.
    return b64encode(string.encode('utf-8')).decode()

def load_config(conffile=None, segment='meshcentral-account'):
    if conffile is None:
        conffile = './api.conf'

    if not os.path.exists(conffile):
        raise ScriptEndTrigger(f'Missing config file {conffile}, unable to initialize. Please provide an alternative path.')

    try:
        my_config = ConfigParser()
        my_config.read(conffile)
    except Exception as err:
        raise ScriptEndTrigger(f'Unable to read config file <{conffile}>: {err}!')

    if segment not in my_config:
        raise ScriptEndTrigger(f'Segment "{segment}" not found in config file <{conffile}>!')

    return my_config[segment]

def translation_function(obj):
    if isinstance(obj, datetime.datetime):
        return obj.isoformat()
    return str(obj)

async def main():
    configuration = load_config()

    async with meshctrl.Session(
        configuration['websocket_url'],
        user=configuration['username'],
        password=configuration['password']
    ) as session:
        await session.initialized.wait()

        async def _(session):
            async for message in session.raw_messages():
                print(message)
        async with asyncio.TaskGroup() as tg:
            tg.create_task(asyncio.wait_for(_(session), timeout=5))
            tg.create_task(session.list_devices(details=False, timeout=5))
            tg.create_task(session.list_devices(details=True, timeout=5))

        for device in raw_devices:
            device = device.__dict__
            print(json.dumps(device, indent=4, default=translation_function))

asyncio.run(main())
```
api.conf
```ini
[meshcentral-account]
websocket_url = wss://<host>/
username = service
password = <the password>

[meshcentral-database]
database_host = 
database_port = 
database = 
username = 
password = 
```
Other than your function change in the recent issues: https://github.com/HuFlungDu/pylibmeshctrl/issues/8 and https://github.com/HuFlungDu/pylibmeshctrl/issues/9#issuecomment-2550160922 everything is stock.

requirements.txt
```yaml
asyncio
libmeshctrl
```

MeshCentral Server 1.1.35

```
(venv) celdrith@N-DESKTOP1:~/meshcaller$ python3 --version
Python 3.11.2
```

Running on
```
(venv) celdrith@N-DESKTOP1:~/meshcaller$ uname -r
5.15.167.4-microsoft-standard-WSL2
```

What info other than this do you need?

**Comment by HuFlungDu** [comment]
Yeah, sure, I'll email you and we can arrange something real quick.

**Comment by DaanSelen** [comment]
Full output by the way:

```
(venv) celdrith@N-DESKTOP1:~/meshcaller$ python3 rewrite.py
{"action":"meshes","meshes":[{"type":"mesh","_id":... A LOT OF DATA... "tag":"meshctrl_list_devices_2"}
  + Exception Group Traceback (most recent call last):
  |   File "/home/celdrith/meshcaller/rewrite.py", line 61, in <module>
  |     asyncio.run(main())
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/home/celdrith/meshcaller/rewrite.py", line 52, in main
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    |     return fut.result()
    |            ^^^^^^^^^^^^
    |   File "/home/celdrith/meshcaller/rewrite.py", line 50, in _
    |     async for message in session.raw_messages():
    |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 533, in raw_messages
    |     data = await event_queue.get()
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/asyncio/queues.py", line 158, in get
    |     await getter
    | asyncio.exceptions.CancelledError
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    |     raise exceptions.TimeoutError() from exc
    | TimeoutError
    +---------------- 2 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 466, in list_devices
    |     async with asyncio.TaskGroup() as tg:
    |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
      |     return fut.result()
      |            ^^^^^^^^^^^^
      |   File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
      |     await fut
      | asyncio.exceptions.CancelledError
      |
      | The above exception was the direct cause of the following exception:
      |
      | Traceback (most recent call last):
      |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/util.py", line 154, in wrapper
      |     return await f(self, *args, **kwargs)
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/celdrith/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 268, in _send_command_no_response_id
      |     await asyncio.wait_for(responded.wait(), timeout=timeout)
      |   File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
      |     raise exceptions.TimeoutError() from exc
      | TimeoutError
      +------------------------------------
(venv) celdrith@N-DESKTOP1:~/meshcaller$
```

**Comment by DaanSelen** [comment]
Progress at last. Changing the type to CSV, DOES give a return... so there lies our problem...

**Comment by DaanSelen** [comment]
Also:

```
        async with asyncio.TaskGroup() as tg:
            tg.create_task(asyncio.wait_for(_(session), timeout=5))
            tg.create_task(session.list_devices(details=False,timeout=5))
            tg.create_task(session.list_devices(details=True, timeout=60))
```

Kills it after 5 sec, so the waitfor is timing out.

**Comment by DaanSelen** [comment]
Somehow different machine, different MeshCentral installation same problem.

**Comment by DaanSelen** [comment]
Tearing down the non-responding machine and rebuilding... All tests responded. So assuming a incident.
