### ISSUE TITLE
perhaps a Feature request but incorrect auth handling

### ISSUE THREAD

**Issue by DaanSelen** [HuFlungDu/pylibmeshctrl#11]
Hello Josiah, good morning.

I am going to prod around and perhaps a request if incorrect authentication can be handled more... gracefully?

```shell
  + Exception Group Traceback (most recent call last):
  |   File "/home/dselen/meshcaller/rewrite.py", line 55, in <module>
  |     asyncio.run(main())
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/home/dselen/meshcaller/rewrite.py", line 41, in main
  |     async with meshctrl.Session(
  |   File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/util.py", line 151, in wrapper
  |     raise self._main_loop_error
  |   File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 151, in _main_loop
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 193, in _listen_data_task
    |     raise exceptions.ServerError("Invalid Auth")
    | meshctrl.exceptions.ServerError: Invalid Auth
    +------------------------------------
```

It is direct and clear from the error though.

**Comment by HuFlungDu** [comment]
What would you suggest? Generally I'm a fan of failures raising exceptions, as it stops me from trying to debug something that is failing because the previous call fails (e.g., you try to log in, but it fails and return "False" from the login function. Next you try to do something, but it fails because you aren't logged in, which disconnects the appearance of the issue from where it actually occurs), but I'm open to suggestions to make it more clear. I just really don't want someone trying to continue using a connection on which the authentication failed.

In general, my view is that Python has very good exception handling, and they should be used pretty liberally.

**Comment by DaanSelen** [comment]
> What would you suggest? Generally I'm a fan of failures raising exceptions, as it stops me from trying to debug something that is failing because the previous call fails (e.g., you try to log in, but it fails and return "False" from the login function. Next you try to do something, but it fails because you aren't logged in, which disconnects the appearance of the issue from where it actually occurs), but I'm open to suggestions to make it more clear. I just really don't want someone trying to continue using a connection on which the authentication failed.
> 
> In general, my view is that Python has very good exception handling, and they should be used pretty liberally.

Its not highly technical but perhaps the program detecting a `Invalid Auth` reponse exits and gives an informative response, now it only does this upon reaching the timeout.

**Comment by HuFlungDu** [comment]
Oh, I see. Because we wait for 10 seconds timeout on _socket_open and initlialized doesn't cancel, it doesn't throw any connection exceptions until after the _socket_open wait times out.

Yep, that's a bug. Shouldn't have to wait 10 seconds for an error we know immediately.

**Comment by DaanSelen** [comment]
> Oh, I see. Because we wait for 10 seconds timeout on _socket_open and initlialized doesn't cancel, it doesn't throw any connection exceptions until after the _socket_open wait times out.
> 
> Yep, that's a bug. Shouldn't have to wait 10 seconds for an error we know immediately.

Exactly! Thanks
