### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by DaanSelen** [HuFlungDu/pylibmeshctrl#8]
Hi @HuFlungDu , I was prodding around with this library:

```
Traceback (most recent call last):
  File "/home/dselen/meshcaller/meshcaller.py", line 2, in <module>
    import meshctrl
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/__init__.py", line 18, in <module>
    from .session import Session
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 16, in <module>
    from . import shell
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/shell.py", line 1, in <module>
    from . import tunnel
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/tunnel.py", line 55
    self.node_id = f"node/{self._session._currentDomain or ""}/{self.node_id}"
                                                                              ^
SyntaxError: f-string: expecting '}'
```
https://github.com/HuFlungDu/pylibmeshctrl/blob/74567437092112b818d77b70fc8c09f4057f9d16/src/meshctrl/tunnel.py#L55C17-L55C28

Changing
```
self.node_id = f"node/{self._session._currentDomain or ""}/{self.node_id}"
```
To
```
self.node_id = f"node/{self._session._currentDomain or ''}/{self.node_id}"
```

Made the error dissapear, can you elaborate?

**Comment by HuFlungDu** [comment]
This seems to be an issue with older versions of python. 3.13 fixes this, but it makes more sense for me to backport all the strings to work with older python versions.
