### ISSUE TITLE
Conversion failing

### ISSUE THREAD

**Issue by DaanSelen** [HuFlungDu/pylibmeshctrl#9]
Inside the Mesh init function, by default the following error is generated when I try to execute this:

```
import asyncio
import meshctrl
import json

url = "<REDAC>"

async def initConnection():
    session = meshctrl.Session(url, user="<REDAC>", password="<REDAC>")
    await session.initialized.wait()
    user = await session.list_device_groups()
    print(user)

    await session.close()

async def main():
    await initConnection()

asyncio.run(main())
```

Error:

```
an error occurred during closing of asynchronous generator <async_generator object Connection.send_context at 0x7f9499d258b0>
asyncgen: <async_generator object Connection.send_context at 0x7f9499d258b0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/meshcaller.py", line 16, in main
    await initConnection()
  File "/home/dselen/meshcaller/meshcaller.py", line 10, in initConnection
    user = await session.list_device_groups()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 327, in list_device_groups
    return [mesh.Mesh(m["_id"], self, **m) for m in data["meshes"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 327, in <listcomp>
    return [mesh.Mesh(m["_id"], self, **m) for m in data["meshes"]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/mesh.py", line 49, in __init__
    created_at = datetime.datetime.fromtimestamp(created_at)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 56519 is out of range

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
Traceback (most recent call last):
  File "/home/dselen/meshcaller/meshcaller.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/meshcaller.py", line 16, in main
    await initConnection()
  File "/home/dselen/meshcaller/meshcaller.py", line 10, in initConnection
    user = await session.list_device_groups()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 327, in list_device_groups
    return [mesh.Mesh(m["_id"], self, **m) for m in data["meshes"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/session.py", line 327, in <listcomp>
    return [mesh.Mesh(m["_id"], self, **m) for m in data["meshes"]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/mesh.py", line 49, in __init__
    created_at = datetime.datetime.fromtimestamp(created_at)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 56519 is out of range
Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<<async_generator_athrow without __name__>()> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.11/asyncio/tasks.py:898, Task.task_wakeup()]>>
```

The following function update solves this issue:

```
if created_at is not None:
            if not isinstance(created_at, datetime.datetime):
                try: # Try to handle both seconds and milliseconds
                    if created_at > 1000000000000:  # Assumption: milliseconds if > 1 trillion
                        created_at = datetime.datetime.fromtimestamp(created_at / 1000.0)
                    else:
                        created_at = datetime.datetime.fromtimestamp(created_at)
                    
                    if created_at.year < 1900 or created_at.year > 2200:
                        raise ValueError("Timestamp year out of range")

                except (OSError, ValueError) as e:
                    print(f"Invalid timestamp: {created_at}. Error: {e}. Using current date instead.")
                    created_at = datetime.datetime.now()  # Set to current time if invalid
            else: # In case the created_at is already a datetime object, no conversion needed.
                pass
```

I am curious to what you think.
If you like the solution, I can create a PR.

**Comment by HuFlungDu** [comment]
What is the mesh creation time here? Meshcentral should return in milliseconds, I guess there can be some value errors. Does this code fix it?:

``` python
        if not isinstance(created_at, datetime.datetime) and created_at is not None:
            try:
                created_at = datetime.datetime.fromtimestamp(created_at)
            except OSError, ValueError:
                # Meshcentral returns in miliseconds, while fromtimestamp, and most of python, expects the argument in seconds. Try seconds frist, then translate from ms if it fails.
                # This doesn't work for really early timestamps, but I don't expect that to be a problem here.
                created_at = datetime.datetime.fromtimestamp(created_at/1000.0)
```

**Comment by DaanSelen** [comment]
My MC returns 56519

**Comment by DaanSelen** [comment]
> What is the mesh creation time here? Meshcentral should return in milliseconds, I guess there can be some value errors. Does this code fix it?:
> 
> ```python
>         if not isinstance(created_at, datetime.datetime) and created_at is not None:
>             try:
>                 created_at = datetime.datetime.fromtimestamp(created_at)
>             except OSError, ValueError:
>                 # Meshcentral returns in miliseconds, while fromtimestamp, and most of python, expects the argument in seconds. Try seconds frist, then translate from ms if it fails.
>                 # This doesn't work for really early timestamps, but I don't expect that to be a problem here.
>                 created_at = datetime.datetime.fromtimestamp(created_at/1000.0)
> ```

I suggest "`except (OSError, ValueError):`" parentheses. I am using Python 3.11 so that might be our incompatibility sometimes!

**Comment by DaanSelen** [comment]
Sorry to give false information, I now get with the updated function:

```
Error occurred: year 56932 is out of range
```

**Comment by DaanSelen** [comment]
Seems to be working! Sorry for me previous comments, I was too quick.

**Comment by HuFlungDu** [comment]
Can you do a similar thing for this as in https://github.com/HuFlungDu/pylibmeshctrl/issues/10#issuecomment-2552118330. I'm trying to replicate the error so I can write a regression test, but I can't find the number for `created_at` that causes it. None of my mesh servers show this same behavior, so I would like to see what MC is returning that causes this issue.

**Comment by DaanSelen** [comment]
Is the value you are looking for:
```shell
  File "/home/dselen/meshcaller/venv/lib/python3.11/site-packages/meshctrl/mesh.py", line 49, in __init__
    created_at = datetime.datetime.fromtimestamp(created_at)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 56519 is out of range
```
Or what value specificly?

**Comment by HuFlungDu** [comment]
When you run list_device_groups, meshcentral returns an object that includes the raw info, then the library will try to turn them into useful info. If you add the raw_messages listener, it will print out the actual values returned from meshcentral, which apparently datetime doesn't put in its exception message.

**Comment by DaanSelen** [comment]
Just for fun, Simon has the same issue on a Mac.
